env:
  browser: true
  es6: true
  node: true

parser: "babel-eslint"

extends:
  - "airbnb"
  - "airbnb/hooks"
  - "prettier"
  - "prettier/react"
  - "plugin:prettier/recommended"

plugins:
  - "react"
  - "prettier"

rules:
  no-plusplus: 0
  react/jsx-props-no-spreading: "off"
  import/prefer-default-export: "off"
  no-console: 
    - "error"
    - allow: 
      - "warn"
      - "error"
  react/jsx-filename-extension:
    - 1
    - extensions: 
      - ".js"
      - ".jsx"