version: '3'

services: 
    front:
        build:
            context: .
            dockerfile: ./docker/prod.Dockerfile
        ports: 
            - 80:80
        environment:
            - REACT_APP_ROMI_API=${REACT_APP_ROMI_API}