name: 'front'

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run build
      run: docker-compose down --volumes && docker-compose build

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Check linting
        run: yarn lint

  tests:
    runs-on: ubuntu-latest
    container: cypress/included:5.1.0
    steps:
      - name: Run tests E2E
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
